
package com.ws.soap.rpc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidatorService", targetNamespace = "http://service.rpc.soap.ws.com/", wsdlLocation = "http://localhost:8080/MyCreditCardService/ValidatorService?wsdl")
public class ValidatorService
    extends Service
{

    private final static URL VALIDATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATORSERVICE_EXCEPTION;
    private final static QName VALIDATORSERVICE_QNAME = new QName("http://service.rpc.soap.ws.com/", "ValidatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MyCreditCardService/ValidatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATORSERVICE_WSDL_LOCATION = url;
        VALIDATORSERVICE_EXCEPTION = e;
    }

    public ValidatorService() {
        super(__getWsdlLocation(), VALIDATORSERVICE_QNAME);
    }

    public ValidatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATORSERVICE_QNAME, features);
    }

    public ValidatorService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATORSERVICE_QNAME);
    }

    public ValidatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATORSERVICE_QNAME, features);
    }

    public ValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardValidator
     */
    @WebEndpoint(name = "CreditCardValidator")
    public CardValidator getCreditCardValidator() {
        return super.getPort(new QName("http://service.rpc.soap.ws.com/", "CreditCardValidator"), CardValidator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardValidator
     */
    @WebEndpoint(name = "CreditCardValidator")
    public CardValidator getCreditCardValidator(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.rpc.soap.ws.com/", "CreditCardValidator"), CardValidator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATORSERVICE_EXCEPTION!= null) {
            throw VALIDATORSERVICE_EXCEPTION;
        }
        return VALIDATORSERVICE_WSDL_LOCATION;
    }

}
