
package com.soap.document.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://service.document.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://service.document.soap.com/", className = "com.soap.document.service.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://service.document.soap.com/", className = "com.soap.document.service.AdditionResponse")
    @Action(input = "http://service.document.soap.com/Calculator/additionRequest", output = "http://service.document.soap.com/Calculator/additionResponse")
    public int addition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substract", targetNamespace = "http://service.document.soap.com/", className = "com.soap.document.service.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://service.document.soap.com/", className = "com.soap.document.service.SubstractResponse")
    @Action(input = "http://service.document.soap.com/Calculator/substractRequest", output = "http://service.document.soap.com/Calculator/substractResponse")
    public int substract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
